### ISSUE TITLE
Error message after deleting an index

### ISSUE THREAD

**Issue by fredcases** [jaeksoft/opensearchserver#1324]
Hello

After deleting an index (within the webapp), I had a pop-in with an error : 
![capture d ecran 2014-12-24 a 15 30 57](https://cloud.githubusercontent.com/assets/8046211/5549099
/ef1d6a9a-8b81-11e4-8694-90b99c09c8b3.png)

The index was correctly deleted in my filesystem

My version is the 1.5.9, build f661a5f424

The error on my oss.log : 

Dec 24, 2014 3:25:35 PM org.zkoss.zk.ui.impl.UiEngineImpl handleError:1362
SEVERE: >>org.zkoss.zk.ui.UiException: Error reading 'apiList' on type com.jaeksoft.searchlib.web.controller.ScriptingController at [file:/var/local/open-search-server/opensearchserver-1.5.9/server/webapps/ROOT/WEB-INF/zul/script/index.zul, line:60]

> > org.zkoss.zel.ELException: Error reading 'apiList' on type com.jaeksoft.searchlib.web.controller.ScriptingController
> > java.lang.NullPointerException
> >      at com.jaeksoft.searchlib.web.controller.CommonController.getRestApiUrl(CommonController.java:130)
> >      at com.jaeksoft.searchlib.web.controller.ScriptingController.getApiList(ScriptingController.java:71)
> >      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> >      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> >      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> >      at java.lang.reflect.Method.invoke(Method.java:606)
> >      at org.zkoss.zel.BeanELResolver.getValue(BeanELResolver.java:89)
> >      at org.zkoss.zel.CompositeELResolver.getValue(CompositeELResolver.java:66)
> >      at org.zkoss.zel.CompositeELResolver.getValue(CompositeELResolver.java:66)
> >      at org.zkoss.xel.zel.XelELResolver.getValue(XelELResolver.java:72)
> >      at org.zkoss.bind.xel.zel.BindELResolver.getValue(BindELResolver.java:69)
> >      at org.zkoss.zel.impl.parser.AstValue.getValue(AstValue.java:177)
> >      at org.zkoss.zel.impl.ValueExpressionImpl.getValue(ValueExpressionImpl.java:184)
> >      at org.zkoss.xel.zel.ELXelExpression.evaluate(ELXelExpression.java:40)
> >      at org.zkoss.bind.impl.BindEvaluatorXImpl.getValue(BindEvaluatorXImpl.java:46)
> >      at org.zkoss.bind.impl.LoadPropertyBindingImpl.load(LoadPropertyBindingImpl.java:62)
> >      at org.zkoss.bind.impl.BinderImpl.doPropertyChange0(BinderImpl.java:390)
> >      at org.zkoss.bind.impl.BinderImpl.doPropertyChange(BinderImpl.java:367)
> >      at org.zkoss.bind.impl.BinderImpl.access$100(BinderImpl.java:107)
> >      at org.zkoss.bind.impl.BinderImpl$QueueListener.onEvent(BinderImpl.java:292)
> >      at org.zkoss.zk.ui.event.impl.DesktopEventQueue$QueueListener.onEvent(DesktopEventQueue.java:150)
> >      at org.zkoss.zk.ui.AbstractComponent.onEvent(AbstractComponent.java:2743)
> >      at org.zkoss.zk.ui.AbstractComponent.service(AbstractComponent.java:2714)
> >      at org.zkoss.zk.ui.AbstractComponent.service(AbstractComponent.java:2655)
> >      at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:136)
> >      at org.zkoss.zk.ui.impl.UiEngineImpl.processEvent(UiEngineImpl.java:1720)
> >      at org.zkoss.zk.ui.impl.UiEngineImpl.process(UiEngineImpl.java:1505)
> >      at org.zkoss.zk.ui.impl.UiEngineImpl.execUpdate(UiEngineImpl.java:1215)
> >      at org.zkoss.zk.au.http.DHtmlUpdateServlet.process(DHtmlUpdateServlet.java:601)
> >      at org.zkoss.zk.au.http.DHtmlUpdateServlet.doGet(DHtmlUpdateServlet.java:483)
> >      at org.zkoss.zk.au.http.DHtmlUpdateServlet.doPost(DHtmlUpdateServlet.java:492)
> >      at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
> >      at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
> >      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
> >      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
> >      at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
> >      at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
> >      at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
> >      at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
> >      at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
> >      at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936)
> >      at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
> >      at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
> >      at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
> >      at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
> >      at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
> >      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> >      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
> >      at java.lang.Thread.run(Thread.java:745)

**Comment by SuriyaaKudoIsc** [comment]
Got same error.
