### ISSUE TITLE
NPE when using join on query

### ISSUE THREAD

**Issue by AlexandreToyer** [jaeksoft/opensearchserver#1473]
In some case when I use join on a search query I get a Null Pointer Exception. Here is the full trace:

```
com.jaeksoft.searchlib.web.ServletException: com.jaeksoft.searchlib.SearchLibException: java.lang.NullPointerException
    at com.jaeksoft.searchlib.web.SelectServlet.doRequest(SelectServlet.java:64)
    at com.jaeksoft.searchlib.web.AbstractServlet.doRequest(AbstractServlet.java:93)
    at com.jaeksoft.searchlib.web.AbstractServlet.doGet(AbstractServlet.java:147)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.jaeksoft.searchlib.SearchLibException: java.lang.NullPointerException
    at com.jaeksoft.searchlib.Client.request(Client.java:410)
    at com.jaeksoft.searchlib.web.SelectServlet.doRequest(SelectServlet.java:59)
    ... 20 more
Caused by: java.lang.NullPointerException
    at com.jaeksoft.searchlib.result.collector.collapsing.CollapseBaseCollector.&lt;init&gt;(CollapseBaseCollector.java:63)
    at com.jaeksoft.searchlib.result.collector.collapsing.CollapseBaseCollector.duplicate(CollapseBaseCollector.java:76)
    at com.jaeksoft.searchlib.result.collector.collapsing.CollapseBaseCollector.duplicate(CollapseBaseCollector.java:35)
    at com.jaeksoft.searchlib.result.collector.AbstractBaseCollector.duplicate(AbstractBaseCollector.java:71)
    at com.jaeksoft.searchlib.result.collector.join.JoinUtils.join(JoinUtils.java:60)
    at com.jaeksoft.searchlib.join.JoinItem.apply(JoinItem.java:424)
    at com.jaeksoft.searchlib.join.JoinList.apply(JoinList.java:114)
    at com.jaeksoft.searchlib.result.ResultSearchSingle.&lt;init&gt;(ResultSearchSingle.java:95)
    at com.jaeksoft.searchlib.request.AbstractSearchRequest.execute(AbstractSearchRequest.java:1291)
    at com.jaeksoft.searchlib.index.ReaderLocal.request(ReaderLocal.java:715)
    at com.jaeksoft.searchlib.index.IndexSingle.request(IndexSingle.java:262)
    at com.jaeksoft.searchlib.Client.request(Client.java:404)
    ... 21 more
Caused by...
com.jaeksoft.searchlib.SearchLibException: java.lang.NullPointerException
    at com.jaeksoft.searchlib.Client.request(Client.java:410)
    at com.jaeksoft.searchlib.web.SelectServlet.doRequest(SelectServlet.java:59)
    at com.jaeksoft.searchlib.web.AbstractServlet.doRequest(AbstractServlet.java:93)
    at com.jaeksoft.searchlib.web.AbstractServlet.doGet(AbstractServlet.java:147)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at com.jaeksoft.searchlib.result.collector.collapsing.CollapseBaseCollector.&lt;init&gt;(CollapseBaseCollector.java:63)
    at com.jaeksoft.searchlib.result.collector.collapsing.CollapseBaseCollector.duplicate(CollapseBaseCollector.java:76)
    at com.jaeksoft.searchlib.result.collector.collapsing.CollapseBaseCollector.duplicate(CollapseBaseCollector.java:35)
    at com.jaeksoft.searchlib.result.collector.AbstractBaseCollector.duplicate(AbstractBaseCollector.java:71)
    at com.jaeksoft.searchlib.result.collector.join.JoinUtils.join(JoinUtils.java:60)
    at com.jaeksoft.searchlib.join.JoinItem.apply(JoinItem.java:424)
    at com.jaeksoft.searchlib.join.JoinList.apply(JoinList.java:114)
    at com.jaeksoft.searchlib.result.ResultSearchSingle.&lt;init&gt;(ResultSearchSingle.java:95)
    at com.jaeksoft.searchlib.request.AbstractSearchRequest.execute(AbstractSearchRequest.java:1291)
    at com.jaeksoft.searchlib.index.ReaderLocal.request(ReaderLocal.java:715)
    at com.jaeksoft.searchlib.index.IndexSingle.request(IndexSingle.java:262)
    at com.jaeksoft.searchlib.Client.request(Client.java:404)
    ... 21 more
Caused by...
java.lang.NullPointerException
    at com.jaeksoft.searchlib.result.collector.collapsing.CollapseBaseCollector.&lt;init&gt;(CollapseBaseCollector.java:63)
    at com.jaeksoft.searchlib.result.collector.collapsing.CollapseBaseCollector.duplicate(CollapseBaseCollector.java:76)
    at com.jaeksoft.searchlib.result.collector.collapsing.CollapseBaseCollector.duplicate(CollapseBaseCollector.java:35)
    at com.jaeksoft.searchlib.result.collector.AbstractBaseCollector.duplicate(AbstractBaseCollector.java:71)
    at com.jaeksoft.searchlib.result.collector.join.JoinUtils.join(JoinUtils.java:60)
    at com.jaeksoft.searchlib.join.JoinItem.apply(JoinItem.java:424)
    at com.jaeksoft.searchlib.join.JoinList.apply(JoinList.java:114)
    at com.jaeksoft.searchlib.result.ResultSearchSingle.&lt;init&gt;(ResultSearchSingle.java:95)
    at com.jaeksoft.searchlib.request.AbstractSearchRequest.execute(AbstractSearchRequest.java:1291)
    at com.jaeksoft.searchlib.index.ReaderLocal.request(ReaderLocal.java:715)
    at com.jaeksoft.searchlib.index.IndexSingle.request(IndexSingle.java:262)
    at com.jaeksoft.searchlib.Client.request(Client.java:404)
    at com.jaeksoft.searchlib.web.SelectServlet.doRequest(SelectServlet.java:59)
    at com.jaeksoft.searchlib.web.AbstractServlet.doRequest(AbstractServlet.java:93)
    at com.jaeksoft.searchlib.web.AbstractServlet.doGet(AbstractServlet.java:147)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by micktion** [comment]
I'm getting an error very similar to this in  v1.5.13 - build 2b6dfa4d90

<?xml version="1.0" encoding="UTF-8"?><response>
<entry key="Status">Error</entry>
<entry key="Exception">com.jaeksoft.searchlib.web.ServletException: com.jaeksoft.searchlib.SearchLibException: java.lang.NullPointerException</entry>
<entry key="Trace">com.jaeksoft.searchlib.web.ServletException: com.jaeksoft.searchlib.SearchLibException: java.lang.NullPointerException&#13;
	at com.jaeksoft.searchlib.web.RendererServlet.doRequest(RendererServlet.java:225)&#13;
	at com.jaeksoft.searchlib.web.AbstractServlet.doRequest(AbstractServlet.java:93)&#13;
	at com.jaeksoft.searchlib.web.AbstractServlet.doGet(AbstractServlet.java:147)&#13;
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)&#13;
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)&#13;
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)&#13;
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)&#13;
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)&#13;
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)&#13;
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)&#13;
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)&#13;
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)&#13;
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)&#13;
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)&#13;
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)&#13;
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)&#13;
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)&#13;
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521)&#13;
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096)&#13;
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674)&#13;
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2500)&#13;
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2489)&#13;
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)&#13;
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)&#13;
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
Caused by: com.jaeksoft.searchlib.SearchLibException: java.lang.NullPointerException&#13;
	at com.jaeksoft.searchlib.Client.request(Client.java:375)&#13;
	at com.jaeksoft.searchlib.web.RendererServlet.doRequest(RendererServlet.java:158)&#13;
	... 25 more&#13;
Caused by: java.lang.NullPointerException&#13;
	at org.apache.lucene.util.SimpleStringInterner.intern(SimpleStringInterner.java:54)&#13;
	at org.apache.lucene.util.StringHelper.intern(StringHelper.java:39)&#13;
	at org.apache.lucene.search.FieldCacheImpl$Entry.&lt;init&gt;(FieldCacheImpl.java:279)&#13;
	at org.apache.lucene.search.FieldCacheImpl.getStringIndex(FieldCacheImpl.java:856)&#13;
	at com.jaeksoft.searchlib.index.ReaderLocal.getStringIndexNoLock(ReaderLocal.java:416)&#13;
	at com.jaeksoft.searchlib.index.ReaderLocal.getStringIndex(ReaderLocal.java:423)&#13;
	at com.jaeksoft.searchlib.collapse.CollapseAbstract.collapseOptimized(CollapseAbstract.java:189)&#13;
	at com.jaeksoft.searchlib.collapse.CollapseAbstract.collapse(CollapseAbstract.java:212)&#13;
	at com.jaeksoft.searchlib.result.ResultSearchSingle.&lt;init&gt;(ResultSearchSingle.java:120)&#13;
	at com.jaeksoft.searchlib.request.AbstractLocalSearchRequest.execute(AbstractLocalSearchRequest.java:265)&#13;
	at com.jaeksoft.searchlib.index.ReaderLocal.request(ReaderLocal.java:711)&#13;
	at com.jaeksoft.searchlib.index.IndexSingle.request(IndexSingle.java:268)&#13;
	at com.jaeksoft.searchlib.Client.request(Client.java:369)&#13;
	... 26 more&#13;
Caused by...&#13;
com.jaeksoft.searchlib.SearchLibException: java.lang.NullPointerException&#13;
	at com.jaeksoft.searchlib.Client.request(Client.java:375)&#13;
	at com.jaeksoft.searchlib.web.RendererServlet.doRequest(RendererServlet.java:158)&#13;
	at com.jaeksoft.searchlib.web.AbstractServlet.doRequest(AbstractServlet.java:93)&#13;
	at com.jaeksoft.searchlib.web.AbstractServlet.doGet(AbstractServlet.java:147)&#13;
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)&#13;
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)&#13;
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)&#13;
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)&#13;
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)&#13;
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)&#13;
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)&#13;
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)&#13;
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)&#13;
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)&#13;
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)&#13;
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)&#13;
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)&#13;
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)&#13;
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521)&#13;
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096)&#13;
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674)&#13;
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2500)&#13;
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2489)&#13;
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)&#13;
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)&#13;
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
Caused by: java.lang.NullPointerException&#13;
	at org.apache.lucene.util.SimpleStringInterner.intern(SimpleStringInterner.java:54)&#13;
	at org.apache.lucene.util.StringHelper.intern(StringHelper.java:39)&#13;
	at org.apache.lucene.search.FieldCacheImpl$Entry.&lt;init&gt;(FieldCacheImpl.java:279)&#13;
	at org.apache.lucene.search.FieldCacheImpl.getStringIndex(FieldCacheImpl.java:856)&#13;
	at com.jaeksoft.searchlib.index.ReaderLocal.getStringIndexNoLock(ReaderLocal.java:416)&#13;
	at com.jaeksoft.searchlib.index.ReaderLocal.getStringIndex(ReaderLocal.java:423)&#13;
	at com.jaeksoft.searchlib.collapse.CollapseAbstract.collapseOptimized(CollapseAbstract.java:189)&#13;
	at com.jaeksoft.searchlib.collapse.CollapseAbstract.collapse(CollapseAbstract.java:212)&#13;
	at com.jaeksoft.searchlib.result.ResultSearchSingle.&lt;init&gt;(ResultSearchSingle.java:120)&#13;
	at com.jaeksoft.searchlib.request.AbstractLocalSearchRequest.execute(AbstractLocalSearchRequest.java:265)&#13;
	at com.jaeksoft.searchlib.index.ReaderLocal.request(ReaderLocal.java:711)&#13;
	at com.jaeksoft.searchlib.index.IndexSingle.request(IndexSingle.java:268)&#13;
	at com.jaeksoft.searchlib.Client.request(Client.java:369)&#13;
	... 26 more&#13;
Caused by...&#13;
java.lang.NullPointerException&#13;
	at org.apache.lucene.util.SimpleStringInterner.intern(SimpleStringInterner.java:54)&#13;
	at org.apache.lucene.util.StringHelper.intern(StringHelper.java:39)&#13;
	at org.apache.lucene.search.FieldCacheImpl$Entry.&lt;init&gt;(FieldCacheImpl.java:279)&#13;
	at org.apache.lucene.search.FieldCacheImpl.getStringIndex(FieldCacheImpl.java:856)&#13;
	at com.jaeksoft.searchlib.index.ReaderLocal.getStringIndexNoLock(ReaderLocal.java:416)&#13;
	at com.jaeksoft.searchlib.index.ReaderLocal.getStringIndex(ReaderLocal.java:423)&#13;
	at com.jaeksoft.searchlib.collapse.CollapseAbstract.collapseOptimized(CollapseAbstract.java:189)&#13;
	at com.jaeksoft.searchlib.collapse.CollapseAbstract.collapse(CollapseAbstract.java:212)&#13;
	at com.jaeksoft.searchlib.result.ResultSearchSingle.&lt;init&gt;(ResultSearchSingle.java:120)&#13;
	at com.jaeksoft.searchlib.request.AbstractLocalSearchRequest.execute(AbstractLocalSearchRequest.java:265)&#13;
	at com.jaeksoft.searchlib.index.ReaderLocal.request(ReaderLocal.java:711)&#13;
	at com.jaeksoft.searchlib.index.IndexSingle.request(IndexSingle.java:268)&#13;
	at com.jaeksoft.searchlib.Client.request(Client.java:369)&#13;
	at com.jaeksoft.searchlib.web.RendererServlet.doRequest(RendererServlet.java:158)&#13;
	at com.jaeksoft.searchlib.web.AbstractServlet.doRequest(AbstractServlet.java:93)&#13;
	at com.jaeksoft.searchlib.web.AbstractServlet.doGet(AbstractServlet.java:147)&#13;
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)&#13;
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)&#13;
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)&#13;
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)&#13;
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)&#13;
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)&#13;
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)&#13;
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)&#13;
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)&#13;
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)&#13;
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)&#13;
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)&#13;
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)&#13;
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)&#13;
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521)&#13;
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096)&#13;
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674)&#13;
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2500)&#13;
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2489)&#13;
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)&#13;
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)&#13;
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
</entry>
</response>
