### ISSUE TITLE
Faceted fields returned in different orders

### ISSUE THREAD

**Issue by caesarcxiv** [jaeksoft/opensearchserver#1641]
Build 36d77ca5eb
After the upgrade faceted fields are being returned in a random order. (we enabled term_asc within each facet)

Example facets setup for fields Division and Guide may be returned in order of Division, Guide or Guide, Division.

Facets should always be returned in a set order (it would be nice if this could be rearranged in interface) to make looping easy.

**Comment by Mojster** [comment]
In 1.5.14 I have a similar problem.
When selecting facet suddenly the order changes.

I agree with caesarcxiv, that order should be fixed.

**Comment by emmanuel-keller** [comment]
This has been fixed in the nightly build:
http://www.open-search-server.com/ftp/OpenSearchServer_2.0/build-3886954/

Can you have a look ?

**Comment by Mojster** [comment]
Cannot start under windows.
Got this error:

> SEVERE: ContainerBase.addChild: start:
> org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].Standa
> rdContext[]]
>         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
>         at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
>         at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
>         at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
>         at org.apache.catalina.startup.Tomcat.addWebapp(Tomcat.java:610)
>         at org.apache.catalina.startup.Tomcat.addWebapp(Tomcat.java:567)
>         at com.jaeksoft.searchlib.Server.start(Server.java:112)
>         at com.jaeksoft.searchlib.Server.start(Server.java:126)
>         at com.jaeksoft.searchlib.Server.main(Server.java:132)
> Caused by: java.lang.NoClassDefFoundError: javax/ws/rs/core/Configuration
>         at java.lang.ClassLoader.defineClass1(Native Method)
>         at java.lang.ClassLoader.defineClass(Unknown Source)
>         at java.security.SecureClassLoader.defineClass(Unknown Source)
>         at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:3205)
>         at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:1373)
>         at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1861)
>         at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1735)
>         at java.lang.ClassLoader.defineClass1(Native Method)
>         at java.lang.ClassLoader.defineClass(Unknown Source)
>         at java.security.SecureClassLoader.defineClass(Unknown Source)
>         at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:3205)
>         at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:1373)
>         at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1861)
>         at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1735)
>         at java.lang.ClassLoader.defineClass1(Native Method)
>         at java.lang.ClassLoader.defineClass(Unknown Source)
>         at java.security.SecureClassLoader.defineClass(Unknown Source)
>         at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:3205)
>         at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:1373)
>         at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1861)
>         at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1735)
>         at org.glassfish.jersey.servlet.init.JerseyServletContainerInitializer.addServletWithExistingRegistration(Jersey
> ServletContainerInitializer.java:305)
>         at org.glassfish.jersey.servlet.init.JerseyServletContainerInitializer.onStartupImpl(JerseyServletContainerIniti
> alizer.java:171)
>         at org.glassfish.jersey.servlet.init.JerseyServletContainerInitializer.onStartup(JerseyServletContainerInitializ
> er.java:144)
>         at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5623)
>         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
>         ... 8 more
> Caused by: java.lang.ClassNotFoundException: javax.ws.rs.core.Configuration
>         at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1892)
>         at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1735)
>         ... 34 more
> 
> Exception in thread "main" java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.Lifecycle
> Exception: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
>         at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:903)
>         at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
>         at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
>         at org.apache.catalina.startup.Tomcat.addWebapp(Tomcat.java:610)
>         at org.apache.catalina.startup.Tomcat.addWebapp(Tomcat.java:567)
>         at com.jaeksoft.searchlib.Server.start(Server.java:112)
>         at com.jaeksoft.searchlib.Server.start(Server.java:126)
>         at com.jaeksoft.searchlib.Server.main(Server.java:132)
