### ISSUE TITLE
Crawler deadlocks after running while serving requests

### ISSUE THREAD

**Issue by robfromca** [jaeksoft/opensearchserver#1659]
More or less each morning (although sometimes more often, sometimes less) when I come in the renderer for the search engine displays the page fine, but actual searches hang indefinitely. The stack trace looks like it shows what looks like the a lot of query threads deadlocked, and a locked crawler thread. Tried to include thread dump but can't attach a .txt file...but description is below with samples.. This is version opensearchserver-1.5.12-b940. 

there are a ton of the port 3001 request answering threads waiting on this lock: 0x00000007806ed920

With a stack trace something like:
```        
- parking to wait for  <0x00000007806ed920> (a java.util.concurrent.locks.ReentrantReadWriteLock$FairSync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(AbstractQueuedSynchronizer.java:964)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1282)
        at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:731)
        at com.jaeksoft.searchlib.index.ReaderLocal.request(ReaderLocal.java:717)
        at com.jaeksoft.searchlib.index.IndexSingle.request(IndexSingle.java:262)
```
Those are on the 3001 port worker threads, which serve up requests as far as I can call, and they all look like that.

The main crawl thread seems to be this guy:

```
"Index: site WebCrawlThread Sat Oct 03 18:25:28 UTC 2015" daemon prio=10 tid=0x00007f93780ef000 nid=0x163b waiting on condition [0x00007f9085b45000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000007806ed920> (a java.util.concurrent.locks.ReentrantReadWriteLock$FairSync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:867)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1197)
        at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lock(ReentrantReadWriteLock.java:945)
        at com.jaeksoft.searchlib.index.ReaderLocal.reload(ReaderLocal.java:459)
        at com.jaeksoft.searchlib.index.IndexSingle.reload(IndexSingle.java:249)
        at com.jaeksoft.searchlib.index.WriterLocal.updateDocumentsNoLock(WriterLocal.java:229)
        at com.jaeksoft.searchlib.index.WriterLocal.updateDocuments(WriterLocal.java:249)
        at com.jaeksoft.searchlib.index.IndexSingle.updateDocuments(IndexSingle.java:220)
        at com.jaeksoft.searchlib.Client.updateDocuments(Client.java:129)
```
Feels like a deadlock, but I haven't tracked it down yet. If I disable the crawl, it works fine for days reliably.

**Comment by emmanuel-keller** [comment]
I think we finally got it. We redesigned the sync/log model. Few tests with stress conditions was successfully done.

A working nightly build is available here:
http://download.opensearchserver.com/OpenSearchServer_1.5/build-73f3d94/
