### ISSUE TITLE
Crawl keeps locking itself

### ISSUE THREAD

**Issue by robfromca** [jaeksoft/opensearchserver#1845]
Shortly after starting a crawl (I think when it's processing the first batch), we see this message in the logs:

```
18:06:45,306 WARN: root - Cannot forcefully unlock a NativeFSLock which is held 
by another indexer component: /xxxxxxxx/data/site/index/write.lock
org.apache.lucene.store.LockReleaseFailedException: Cannot forcefully unlock a NativeFSLock which is held by another indexer component: /xxxxxxxx/data/site/index/write.lock
        at org.apache.lucene.store.NativeFSLock.release(NativeFSLockFactory.java:295)
        at org.apache.lucene.index.IndexWriter.unlock(IndexWriter.java:4624)
        at com.jaeksoft.searchlib.index.IndexDirectory.unlock(IndexDirectory.java:119)
        at com.jaeksoft.searchlib.index.WriterLocal.close(WriterLocal.java:93)
        at com.jaeksoft.searchlib.index.WriterLocal.updateDocumentsNoLock(WriterLocal.java:240)
        at com.jaeksoft.searchlib.index.WriterLocal.updateDocuments(WriterLocal.java:249)
        at com.jaeksoft.searchlib.index.IndexSingle.updateDocuments(IndexSingle.java:220)
        at com.jaeksoft.searchlib.Client.updateDocuments(Client.java:129)
        at com.jaeksoft.searchlib.crawler.web.database.UrlManager.updateCrawlTarget(UrlManager.java:636)
        at com.jaeksoft.searchlib.crawler.web.database.UrlCrawlQueue.updateCrawls(UrlCrawlQueue.java:191)
        at com.jaeksoft.searchlib.crawler.web.database.UrlCrawlQueue.indexWork(UrlCrawlQueue.java:167)
        at com.jaeksoft.searchlib.crawler.common.process.CrawlQueueAbstract.index(CrawlQueueAbstract.java:128)
        at com.jaeksoft.searchlib.crawler.web.process.WebCrawlThread.runner(WebCrawlThread.java:137)
        at com.jaeksoft.searchlib.process.ThreadAbstract.run(ThreadAbstract.java:291)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
```

Then a few seconds later:

```
18:06:48,360 ERROR: root - org.apache.lucene.store.LockObtainFailedException: Lock obtain timed out: NativeFSLock@/xxxxxxxx/data/site/index/write.lock
com.jaeksoft.searchlib.SearchLibException: org.apache.lucene.store.LockObtainFailedException: Lock obtain timed out: NativeFSLock@/xxxxxxxx/data/site/index/write.lock
        at com.jaeksoft.searchlib.index.WriterLocal.updateDocumentsNoLock(WriterLocal.java:236)
        at com.jaeksoft.searchlib.index.WriterLocal.updateDocuments(WriterLocal.java:249)
        at com.jaeksoft.searchlib.index.IndexSingle.updateDocuments(IndexSingle.java:220)
        at com.jaeksoft.searchlib.Client.updateDocuments(Client.java:129)
        at com.jaeksoft.searchlib.crawler.web.database.UrlManager.updateCrawlTarget(UrlManager.java:636)
        at com.jaeksoft.searchlib.crawler.web.database.UrlCrawlQueue.updateCrawls(UrlCrawlQueue.java:191)
        at com.jaeksoft.searchlib.crawler.web.database.UrlCrawlQueue.indexWork(UrlCrawlQueue.java:167)
        at com.jaeksoft.searchlib.crawler.common.process.CrawlQueueAbstract.index(CrawlQueueAbstract.java:128)
        at com.jaeksoft.searchlib.crawler.web.process.WebCrawlMaster.runner(WebCrawlMaster.java:155)
        at com.jaeksoft.searchlib.process.ThreadAbstract.run(ThreadAbstract.java:291)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: org.apache.lucene.store.LockObtainFailedException: Lock obtain timed out: NativeFSLock@/xxxxxxxx/data/site/index/write.lock
        at org.apache.lucene.store.Lock.obtain(Lock.java:84)
        at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:1098)
        at com.jaeksoft.searchlib.index.WriterLocal.open(WriterLocal.java:123)
        at com.jaeksoft.searchlib.index.WriterLocal.open(WriterLocal.java:127)
        at com.jaeksoft.searchlib.index.WriterLocal.updateDocumentsNoLock(WriterLocal.java:221)
        ... 12 more
```

I can stop the server and the write.lock file persists. Deleting the write.lock file doesn't help, when it gets to committing the index, the same problem happens again.

This is open search 1.5.14, on 
JDK java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)

With a 3GB heap.

**Comment by luksol** [comment]
I know that this is an old issue, but I have just run into the same problem. Was it ever solved or solution/cause determined?
